apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        #        image: nginx:1.14.2  # ECS Container 로 수정
        image: 629595896805.dkr.ecr.ap-northeast-2.amazonaws.com/jenkins-ecr:v0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
